# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_preferiti_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_file_preferiti_window(object):
    def setupUi(self, file_preferiti_window):
        file_preferiti_window.setObjectName("file_preferiti_window")
        file_preferiti_window.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/MGrep.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        file_preferiti_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(file_preferiti_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.b_backup_line = QtWidgets.QPushButton(self.centralwidget)
        self.b_backup_line.setMinimumSize(QtCore.QSize(30, 30))
        self.b_backup_line.setMaximumSize(QtCore.QSize(30, 30))
        self.b_backup_line.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/zip.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_backup_line.setIcon(icon1)
        self.b_backup_line.setObjectName("b_backup_line")
        self.gridLayout.addWidget(self.b_backup_line, 0, 11, 1, 1)
        self.b_sposta_giu = QtWidgets.QPushButton(self.centralwidget)
        self.b_sposta_giu.setMinimumSize(QtCore.QSize(30, 30))
        self.b_sposta_giu.setMaximumSize(QtCore.QSize(30, 30))
        self.b_sposta_giu.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/down.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_sposta_giu.setIcon(icon2)
        self.b_sposta_giu.setObjectName("b_sposta_giu")
        self.gridLayout.addWidget(self.b_sposta_giu, 0, 5, 1, 1)
        self.b_pubblica_icom = QtWidgets.QPushButton(self.centralwidget)
        self.b_pubblica_icom.setMinimumSize(QtCore.QSize(30, 30))
        self.b_pubblica_icom.setMaximumSize(QtCore.QSize(30, 30))
        self.b_pubblica_icom.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/icom.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_pubblica_icom.setIcon(icon3)
        self.b_pubblica_icom.setObjectName("b_pubblica_icom")
        self.gridLayout.addWidget(self.b_pubblica_icom, 0, 13, 1, 1)
        self.b_delete_line = QtWidgets.QPushButton(self.centralwidget)
        self.b_delete_line.setMinimumSize(QtCore.QSize(30, 30))
        self.b_delete_line.setMaximumSize(QtCore.QSize(30, 30))
        self.b_delete_line.setToolTip("")
        self.b_delete_line.setStatusTip("")
        self.b_delete_line.setWhatsThis("")
        self.b_delete_line.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/failed.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_delete_line.setIcon(icon4)
        self.b_delete_line.setObjectName("b_delete_line")
        self.gridLayout.addWidget(self.b_delete_line, 0, 6, 1, 1)
        self.b_compile_icom_backup1 = QtWidgets.QPushButton(self.centralwidget)
        self.b_compile_icom_backup1.setMinimumSize(QtCore.QSize(30, 30))
        self.b_compile_icom_backup1.setMaximumSize(QtCore.QSize(30, 30))
        self.b_compile_icom_backup1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/icom_backup.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_compile_icom_backup1.setIcon(icon5)
        self.b_compile_icom_backup1.setObjectName("b_compile_icom_backup1")
        self.gridLayout.addWidget(self.b_compile_icom_backup1, 0, 14, 1, 1)
        self.b_compile_icom_backup2 = QtWidgets.QPushButton(self.centralwidget)
        self.b_compile_icom_backup2.setMinimumSize(QtCore.QSize(30, 30))
        self.b_compile_icom_backup2.setMaximumSize(QtCore.QSize(30, 30))
        self.b_compile_icom_backup2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/icom_backup_2.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_compile_icom_backup2.setIcon(icon6)
        self.b_compile_icom_backup2.setObjectName("b_compile_icom_backup2")
        self.gridLayout.addWidget(self.b_compile_icom_backup2, 0, 15, 1, 1)
        self.b_sposta_su = QtWidgets.QPushButton(self.centralwidget)
        self.b_sposta_su.setMinimumSize(QtCore.QSize(30, 30))
        self.b_sposta_su.setMaximumSize(QtCore.QSize(30, 30))
        self.b_sposta_su.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/up.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_sposta_su.setIcon(icon7)
        self.b_sposta_su.setObjectName("b_sposta_su")
        self.gridLayout.addWidget(self.b_sposta_su, 0, 4, 1, 1)
        self.b_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.b_refresh.setMinimumSize(QtCore.QSize(30, 30))
        self.b_refresh.setMaximumSize(QtCore.QSize(30, 30))
        self.b_refresh.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/refresh.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_refresh.setIcon(icon8)
        self.b_refresh.setObjectName("b_refresh")
        self.gridLayout.addWidget(self.b_refresh, 0, 2, 1, 1)
        self.b_clear = QtWidgets.QPushButton(self.centralwidget)
        self.b_clear.setMinimumSize(QtCore.QSize(30, 30))
        self.b_clear.setMaximumSize(QtCore.QSize(30, 30))
        self.b_clear.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/clear.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_clear.setIcon(icon9)
        self.b_clear.setObjectName("b_clear")
        self.gridLayout.addWidget(self.b_clear, 0, 7, 1, 1)
        self.b_insert_line = QtWidgets.QPushButton(self.centralwidget)
        self.b_insert_line.setMinimumSize(QtCore.QSize(30, 30))
        self.b_insert_line.setMaximumSize(QtCore.QSize(30, 30))
        self.b_insert_line.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/line.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_insert_line.setIcon(icon10)
        self.b_insert_line.setObjectName("b_insert_line")
        self.gridLayout.addWidget(self.b_insert_line, 0, 3, 1, 1)
        self.b_save = QtWidgets.QPushButton(self.centralwidget)
        self.b_save.setMinimumSize(QtCore.QSize(30, 30))
        self.b_save.setMaximumSize(QtCore.QSize(30, 30))
        self.b_save.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/disk.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_save.setIcon(icon11)
        self.b_save.setObjectName("b_save")
        self.gridLayout.addWidget(self.b_save, 0, 8, 1, 1)
        self.l_titolo2 = QtWidgets.QLabel(self.centralwidget)
        self.l_titolo2.setObjectName("l_titolo2")
        self.gridLayout.addWidget(self.l_titolo2, 0, 9, 1, 1)
        self.l_titolo1 = QtWidgets.QLabel(self.centralwidget)
        self.l_titolo1.setObjectName("l_titolo1")
        self.gridLayout.addWidget(self.l_titolo1, 0, 0, 1, 2)
        self.b_compile_smile_backup1 = QtWidgets.QPushButton(self.centralwidget)
        self.b_compile_smile_backup1.setMinimumSize(QtCore.QSize(30, 30))
        self.b_compile_smile_backup1.setMaximumSize(QtCore.QSize(30, 30))
        self.b_compile_smile_backup1.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/smile_backup.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_compile_smile_backup1.setIcon(icon12)
        self.b_compile_smile_backup1.setObjectName("b_compile_smile_backup1")
        self.gridLayout.addWidget(self.b_compile_smile_backup1, 0, 16, 1, 1)
        self.b_compile_smile_backup2 = QtWidgets.QPushButton(self.centralwidget)
        self.b_compile_smile_backup2.setMinimumSize(QtCore.QSize(30, 30))
        self.b_compile_smile_backup2.setMaximumSize(QtCore.QSize(30, 30))
        self.b_compile_smile_backup2.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/smile_backup_2.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_compile_smile_backup2.setIcon(icon13)
        self.b_compile_smile_backup2.setObjectName("b_compile_smile_backup2")
        self.gridLayout.addWidget(self.b_compile_smile_backup2, 0, 17, 1, 1)
        self.b_open_folder = QtWidgets.QPushButton(self.centralwidget)
        self.b_open_folder.setMinimumSize(QtCore.QSize(30, 30))
        self.b_open_folder.setMaximumSize(QtCore.QSize(30, 30))
        self.b_open_folder.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/folder.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_open_folder.setIcon(icon14)
        self.b_open_folder.setObjectName("b_open_folder")
        self.gridLayout.addWidget(self.b_open_folder, 0, 10, 1, 1)
        self.b_pubblica_smile = QtWidgets.QPushButton(self.centralwidget)
        self.b_pubblica_smile.setMinimumSize(QtCore.QSize(30, 30))
        self.b_pubblica_smile.setMaximumSize(QtCore.QSize(30, 30))
        self.b_pubblica_smile.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/upload1.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_pubblica_smile.setIcon(icon15)
        self.b_pubblica_smile.setObjectName("b_pubblica_smile")
        self.gridLayout.addWidget(self.b_pubblica_smile, 0, 12, 1, 1)
        self.o_lst1 = QtWidgets.QListView(self.centralwidget)
        self.o_lst1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.o_lst1.setObjectName("o_lst1")
        self.gridLayout.addWidget(self.o_lst1, 8, 0, 1, 18)
        file_preferiti_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(file_preferiti_window)
        self.statusbar.setObjectName("statusbar")
        file_preferiti_window.setStatusBar(self.statusbar)
        self.l_titolo2.setBuddy(self.b_open_folder)
        self.l_titolo1.setBuddy(self.b_refresh)

        self.retranslateUi(file_preferiti_window)
        self.b_refresh.clicked.connect(file_preferiti_window.slot_refresh)
        self.b_insert_line.clicked.connect(file_preferiti_window.slot_insert_line)
        self.b_sposta_su.clicked.connect(file_preferiti_window.slot_sposta_su)
        self.b_sposta_giu.clicked.connect(file_preferiti_window.slot_sposta_giu)
        self.b_delete_line.clicked.connect(file_preferiti_window.slot_delete_line)
        self.b_clear.clicked.connect(file_preferiti_window.slot_clear)
        self.b_save.clicked.connect(file_preferiti_window.slot_save)
        self.b_open_folder.clicked.connect(file_preferiti_window.slot_open_folder)
        self.b_backup_line.clicked.connect(file_preferiti_window.slot_backup_line)
        self.b_pubblica_smile.clicked.connect(file_preferiti_window.slot_pubblica_smile)
        self.b_pubblica_icom.clicked.connect(file_preferiti_window.slot_pubblica_icom)
        self.b_compile_icom_backup1.clicked.connect(file_preferiti_window.slot_compile_icom_backup1)
        self.b_compile_icom_backup2.clicked.connect(file_preferiti_window.slot_compile_icom_backup2)
        self.b_compile_smile_backup1.clicked.connect(file_preferiti_window.slot_compile_smile_backup1)
        self.b_compile_smile_backup2.clicked.connect(file_preferiti_window.slot_compile_smile_backup2)
        self.o_lst1.doubleClicked['QModelIndex'].connect(file_preferiti_window.slot_doppio_click_lista)
        QtCore.QMetaObject.connectSlotsByName(file_preferiti_window)
        file_preferiti_window.setTabOrder(self.b_refresh, self.b_insert_line)
        file_preferiti_window.setTabOrder(self.b_insert_line, self.b_sposta_su)
        file_preferiti_window.setTabOrder(self.b_sposta_su, self.b_sposta_giu)
        file_preferiti_window.setTabOrder(self.b_sposta_giu, self.b_delete_line)
        file_preferiti_window.setTabOrder(self.b_delete_line, self.b_clear)
        file_preferiti_window.setTabOrder(self.b_clear, self.b_save)
        file_preferiti_window.setTabOrder(self.b_save, self.b_open_folder)
        file_preferiti_window.setTabOrder(self.b_open_folder, self.b_backup_line)
        file_preferiti_window.setTabOrder(self.b_backup_line, self.b_pubblica_smile)
        file_preferiti_window.setTabOrder(self.b_pubblica_smile, self.b_pubblica_icom)
        file_preferiti_window.setTabOrder(self.b_pubblica_icom, self.b_compile_icom_backup1)
        file_preferiti_window.setTabOrder(self.b_compile_icom_backup1, self.b_compile_icom_backup2)
        file_preferiti_window.setTabOrder(self.b_compile_icom_backup2, self.b_compile_smile_backup1)
        file_preferiti_window.setTabOrder(self.b_compile_smile_backup1, self.b_compile_smile_backup2)
        file_preferiti_window.setTabOrder(self.b_compile_smile_backup2, self.o_lst1)

    def retranslateUi(self, file_preferiti_window):
        _translate = QtCore.QCoreApplication.translate
        file_preferiti_window.setWindowTitle(_translate("file_preferiti_window", "My favorites files"))
        self.b_sposta_giu.setToolTip(_translate("file_preferiti_window", "<html><head/><body><p>Add the selected line to \'My favorites files</p></body></html>"))
        self.b_sposta_su.setToolTip(_translate("file_preferiti_window", "<html><head/><body><p>Save the search data in order to be retrieved at the next start of SmiGrep</p></body></html>"))
        self.l_titolo2.setText(_translate("file_preferiti_window", "Item actions:"))
        self.l_titolo1.setText(_translate("file_preferiti_window", "List actions:"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    file_preferiti_window = QtWidgets.QMainWindow()
    ui = Ui_file_preferiti_window()
    ui.setupUi(file_preferiti_window)
    file_preferiti_window.show()
    sys.exit(app.exec_())

