# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MGrep_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/MGrep.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSearch = QtWidgets.QMenu(self.menubar)
        self.menuSearch.setObjectName("menuSearch")
        self.menuBooks = QtWidgets.QMenu(self.menubar)
        self.menuBooks.setObjectName("menuBooks")
        self.menuOracle = QtWidgets.QMenu(self.menubar)
        self.menuOracle.setObjectName("menuOracle")
        self.menuFavorites = QtWidgets.QMenu(self.menubar)
        self.menuFavorites.setObjectName("menuFavorites")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_the_windows_position = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/disk.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_the_windows_position.setIcon(icon1)
        self.actionSave_the_windows_position.setObjectName("actionSave_the_windows_position")
        self.actionReset_main_window_position = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/centre.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset_main_window_position.setIcon(icon2)
        self.actionReset_main_window_position.setObjectName("actionReset_main_window_position")
        self.actionFactory_reset = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/factory.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFactory_reset.setIcon(icon3)
        self.actionFactory_reset.setObjectName("actionFactory_reset")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/kill.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionSearch_string = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/search_string.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSearch_string.setIcon(icon5)
        self.actionSearch_string.setObjectName("actionSearch_string")
        self.actionFiles_in_system = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../icons/search_file.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFiles_in_system.setIcon(icon6)
        self.actionFiles_in_system.setObjectName("actionFiles_in_system")
        self.actionImage_link_in_web_page = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../icons/paint.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImage_link_in_web_page.setIcon(icon7)
        self.actionImage_link_in_web_page.setObjectName("actionImage_link_in_web_page")
        self.actionPhone_book = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../icons/phone.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPhone_book.setIcon(icon8)
        self.actionPhone_book.setObjectName("actionPhone_book")
        self.actionEmail_book = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../icons/mail.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEmail_book.setIcon(icon9)
        self.actionEmail_book.setObjectName("actionEmail_book")
        self.actionRecompiler = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../icons/gears.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecompiler.setIcon(icon10)
        self.actionRecompiler.setObjectName("actionRecompiler")
        self.actionLooks = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../icons/lock.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLooks.setIcon(icon11)
        self.actionLooks.setObjectName("actionLooks")
        self.actionSessions = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../icons/table.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSessions.setIcon(icon12)
        self.actionSessions.setObjectName("actionSessions")
        self.actionJobs_status = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../icons/oracle.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJobs_status.setIcon(icon13)
        self.actionJobs_status.setObjectName("actionJobs_status")
        self.actionTables_sizes = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../icons/compile.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTables_sizes.setIcon(icon14)
        self.actionTables_sizes.setObjectName("actionTables_sizes")
        self.actionFiles = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../icons/favorites_files.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFiles.setIcon(icon15)
        self.actionFiles.setObjectName("actionFiles")
        self.actionDirectories = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../icons/favorites_directories.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDirectories.setIcon(icon16)
        self.actionDirectories.setObjectName("actionDirectories")
        self.actionImport_Export = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../icons/db.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport_Export.setIcon(icon17)
        self.actionImport_Export.setObjectName("actionImport_Export")
        self.actionAscii_Graphics_generator = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("../icons/font.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAscii_Graphics_generator.setIcon(icon18)
        self.actionAscii_Graphics_generator.setObjectName("actionAscii_Graphics_generator")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("../icons/help.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon19)
        self.actionHelp.setObjectName("actionHelp")
        self.actionProgram_info = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("../icons/info.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProgram_info.setIcon(icon20)
        self.actionProgram_info.setObjectName("actionProgram_info")
        self.actionChange_log = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("../icons/history.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChange_log.setIcon(icon21)
        self.actionChange_log.setObjectName("actionChange_log")
        self.actionConsole = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("../icons/console.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConsole.setIcon(icon22)
        self.actionConsole.setObjectName("actionConsole")
        self.menuFile.addAction(self.actionSave_the_windows_position)
        self.menuFile.addAction(self.actionReset_main_window_position)
        self.menuFile.addAction(self.actionFactory_reset)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSearch.addAction(self.actionSearch_string)
        self.menuSearch.addAction(self.actionFiles_in_system)
        self.menuSearch.addSeparator()
        self.menuSearch.addAction(self.actionImage_link_in_web_page)
        self.menuBooks.addAction(self.actionPhone_book)
        self.menuBooks.addAction(self.actionEmail_book)
        self.menuOracle.addAction(self.actionRecompiler)
        self.menuOracle.addAction(self.actionLooks)
        self.menuOracle.addAction(self.actionSessions)
        self.menuOracle.addAction(self.actionJobs_status)
        self.menuOracle.addAction(self.actionTables_sizes)
        self.menuFavorites.addAction(self.actionFiles)
        self.menuFavorites.addAction(self.actionDirectories)
        self.menuTools.addAction(self.actionImport_Export)
        self.menuTools.addAction(self.actionAscii_Graphics_generator)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionProgram_info)
        self.menuHelp.addAction(self.actionChange_log)
        self.menuHelp.addAction(self.actionConsole)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSearch.menuAction())
        self.menubar.addAction(self.menuBooks.menuAction())
        self.menubar.addAction(self.menuOracle.menuAction())
        self.menubar.addAction(self.menuFavorites.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MGrep 2.0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSearch.setTitle(_translate("MainWindow", "Search"))
        self.menuBooks.setTitle(_translate("MainWindow", "Books"))
        self.menuOracle.setTitle(_translate("MainWindow", "Oracle"))
        self.menuFavorites.setTitle(_translate("MainWindow", "Favorites"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave_the_windows_position.setText(_translate("MainWindow", "Save the windows position"))
        self.actionReset_main_window_position.setText(_translate("MainWindow", "Reset main window position"))
        self.actionFactory_reset.setText(_translate("MainWindow", "Factory reset"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSearch_string.setText(_translate("MainWindow", "String in the code source"))
        self.actionFiles_in_system.setText(_translate("MainWindow", "Files in system"))
        self.actionImage_link_in_web_page.setText(_translate("MainWindow", "Image link in web page"))
        self.actionPhone_book.setText(_translate("MainWindow", "Phone book"))
        self.actionEmail_book.setText(_translate("MainWindow", "Email book"))
        self.actionRecompiler.setText(_translate("MainWindow", "Recompiler"))
        self.actionLooks.setText(_translate("MainWindow", "Looks"))
        self.actionSessions.setText(_translate("MainWindow", "Sessions"))
        self.actionJobs_status.setText(_translate("MainWindow", "Jobs status"))
        self.actionTables_sizes.setText(_translate("MainWindow", "Tables sizes"))
        self.actionFiles.setText(_translate("MainWindow", "Files"))
        self.actionDirectories.setText(_translate("MainWindow", "Directories"))
        self.actionImport_Export.setText(_translate("MainWindow", "Import-Export"))
        self.actionAscii_Graphics_generator.setText(_translate("MainWindow", "Ascii Graphics generator"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionProgram_info.setText(_translate("MainWindow", "Program info"))
        self.actionChange_log.setText(_translate("MainWindow", "Change log"))
        self.actionConsole.setText(_translate("MainWindow", "Console"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

