# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ricerca_file_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ricerca_file_window(object):
    def setupUi(self, Ricerca_file_window):
        Ricerca_file_window.setObjectName("Ricerca_file_window")
        Ricerca_file_window.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/MGrep.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ricerca_file_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Ricerca_file_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.b_pathname = QtWidgets.QPushButton(self.centralwidget)
        self.b_pathname.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/folder.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_pathname.setIcon(icon1)
        self.b_pathname.setObjectName("b_pathname")
        self.gridLayout.addWidget(self.b_pathname, 0, 11, 1, 1)
        self.l_excludepath = QtWidgets.QLabel(self.centralwidget)
        self.l_excludepath.setObjectName("l_excludepath")
        self.gridLayout.addWidget(self.l_excludepath, 3, 4, 1, 4)
        self.l_pathname_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_pathname_2.setObjectName("l_pathname_2")
        self.gridLayout.addWidget(self.l_pathname_2, 0, 4, 1, 4)
        self.c_cache_file_system = QtWidgets.QCheckBox(self.centralwidget)
        self.c_cache_file_system.setChecked(True)
        self.c_cache_file_system.setObjectName("c_cache_file_system")
        self.gridLayout.addWidget(self.c_cache_file_system, 4, 4, 1, 7)
        self.e_excludepath = QtWidgets.QLineEdit(self.centralwidget)
        self.e_excludepath.setObjectName("e_excludepath")
        self.gridLayout.addWidget(self.e_excludepath, 3, 8, 1, 3)
        self.e_pathname = QtWidgets.QLineEdit(self.centralwidget)
        self.e_pathname.setObjectName("e_pathname")
        self.gridLayout.addWidget(self.e_pathname, 0, 8, 1, 3)
        self.e_filesearch = QtWidgets.QLineEdit(self.centralwidget)
        self.e_filesearch.setObjectName("e_filesearch")
        self.gridLayout.addWidget(self.e_filesearch, 0, 2, 1, 1)
        self.b_excludepath = QtWidgets.QPushButton(self.centralwidget)
        self.b_excludepath.setText("")
        self.b_excludepath.setIcon(icon1)
        self.b_excludepath.setObjectName("b_excludepath")
        self.gridLayout.addWidget(self.b_excludepath, 3, 11, 1, 1)
        self.l_filesearch = QtWidgets.QLabel(self.centralwidget)
        self.l_filesearch.setObjectName("l_filesearch")
        self.gridLayout.addWidget(self.l_filesearch, 0, 0, 1, 2)
        self.l_filter = QtWidgets.QLabel(self.centralwidget)
        self.l_filter.setObjectName("l_filter")
        self.gridLayout.addWidget(self.l_filter, 1, 4, 1, 1)
        self.b_add_line = QtWidgets.QPushButton(self.centralwidget)
        self.b_add_line.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/add.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_add_line.setIcon(icon2)
        self.b_add_line.setObjectName("b_add_line")
        self.gridLayout.addWidget(self.b_add_line, 7, 5, 1, 3)
        self.b_save_pref = QtWidgets.QPushButton(self.centralwidget)
        self.b_save_pref.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/disk.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_save_pref.setIcon(icon3)
        self.b_save_pref.setObjectName("b_save_pref")
        self.gridLayout.addWidget(self.b_save_pref, 7, 4, 1, 1)
        self.e_filter = QtWidgets.QLineEdit(self.centralwidget)
        self.e_filter.setObjectName("e_filter")
        self.gridLayout.addWidget(self.e_filter, 1, 8, 2, 3)
        self.l_risultati = QtWidgets.QLabel(self.centralwidget)
        self.l_risultati.setObjectName("l_risultati")
        self.gridLayout.addWidget(self.l_risultati, 8, 0, 1, 1)
        self.o_lst1 = QtWidgets.QListView(self.centralwidget)
        self.o_lst1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.o_lst1.setObjectName("o_lst1")
        self.gridLayout.addWidget(self.o_lst1, 9, 0, 1, 14)
        self.b_search = QtWidgets.QPushButton(self.centralwidget)
        self.b_search.setToolTip("")
        self.b_search.setStatusTip("")
        self.b_search.setWhatsThis("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/go.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_search.setIcon(icon4)
        self.b_search.setObjectName("b_search")
        self.gridLayout.addWidget(self.b_search, 7, 8, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 12, 1, 1)
        Ricerca_file_window.setCentralWidget(self.centralwidget)
        self.l_excludepath.setBuddy(self.e_excludepath)
        self.l_pathname_2.setBuddy(self.e_pathname)
        self.l_filesearch.setBuddy(self.e_filesearch)
        self.l_filter.setBuddy(self.e_filter)

        self.retranslateUi(Ricerca_file_window)
        self.o_lst1.doubleClicked['QModelIndex'].connect(Ricerca_file_window.o_lst1_slot)
        self.b_save_pref.clicked.connect(Ricerca_file_window.b_save_slot)
        self.b_add_line.clicked.connect(Ricerca_file_window.b_add_line_slot)
        self.b_pathname.clicked.connect(Ricerca_file_window.b_pathname_slot)
        self.b_excludepath.clicked.connect(Ricerca_file_window.b_excludepath_slot)
        self.b_search.clicked.connect(Ricerca_file_window.b_search_slot)
        QtCore.QMetaObject.connectSlotsByName(Ricerca_file_window)
        Ricerca_file_window.setTabOrder(self.e_filesearch, self.e_pathname)
        Ricerca_file_window.setTabOrder(self.e_pathname, self.b_pathname)
        Ricerca_file_window.setTabOrder(self.b_pathname, self.e_filter)
        Ricerca_file_window.setTabOrder(self.e_filter, self.e_excludepath)
        Ricerca_file_window.setTabOrder(self.e_excludepath, self.b_excludepath)
        Ricerca_file_window.setTabOrder(self.b_excludepath, self.c_cache_file_system)
        Ricerca_file_window.setTabOrder(self.c_cache_file_system, self.b_save_pref)
        Ricerca_file_window.setTabOrder(self.b_save_pref, self.b_add_line)
        Ricerca_file_window.setTabOrder(self.b_add_line, self.b_search)
        Ricerca_file_window.setTabOrder(self.b_search, self.o_lst1)

    def retranslateUi(self, Ricerca_file_window):
        _translate = QtCore.QCoreApplication.translate
        Ricerca_file_window.setWindowTitle(_translate("Ricerca_file_window", "Search file in system"))
        self.l_excludepath.setText(_translate("Ricerca_file_window", "Exclude directories"))
        self.l_pathname_2.setText(_translate("Ricerca_file_window", "Folder name"))
        self.c_cache_file_system.setText(_translate("Ricerca_file_window", "Clear cache file system"))
        self.l_filesearch.setText(_translate("Ricerca_file_window", "File search"))
        self.l_filter.setText(_translate("Ricerca_file_window", "File filter"))
        self.b_add_line.setToolTip(_translate("Ricerca_file_window", "<html><head/><body><p>Add the selected line to \'My favorites files</p></body></html>"))
        self.b_save_pref.setToolTip(_translate("Ricerca_file_window", "<html><head/><body><p>Save the search data in order to be retrieved at the next start of SmiGrep</p></body></html>"))
        self.l_risultati.setText(_translate("Ricerca_file_window", "Result:"))
        self.b_search.setText(_translate("Ricerca_file_window", "Start search"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ricerca_file_window = QtWidgets.QMainWindow()
    ui = Ui_Ricerca_file_window()
    ui.setupUi(Ricerca_file_window)
    Ricerca_file_window.show()
    sys.exit(app.exec_())
